"""Regressions for the invariant algebra of the fixed basis group.

Fork B is frozen: h = p*I, G = T^2 x| S_2, so every group element is h-unitary
and acts by M -> B M B^dagger.  Evaluator-side algebra only; no candidate kernel.

Note on scope: proposition IA-3 (Q is not polynomially generated by {A, P, Abar,
Pbar}) is an analytic statement and CANNOT be established by any pointwise
numerical test -- pointwise, Q is determined by z1 (proposition IA-4, locked below).
The analytic proof lives in docs/STAGE5C_D1_4_INVARIANT_ALGEBRA.md section 5.
"""

from itertools import combinations, product

import numpy as np

SWAP = np.array([[0.0, 1.0], [1.0, 0.0]], dtype=complex)
GRID = (0.0, 1.0, -1.0, 1j, -1j)


def holomorphic_family(m):
    a, b, c, d = m[0, 0], m[0, 1], m[1, 0], m[1, 1]
    return (a + d, a * d, b * c)


def real_family(m):
    a, b, c, d = m[0, 0], m[0, 1], m[1, 0], m[1, 1]
    u, v = abs(b) ** 2, abs(c) ** 2
    return (a + d, a * d, b * c, u + v, abs(a - d) ** 2, (a - d) * (u - v))


def _rounded(values, digits=9):
    return tuple(
        complex(round(complex(z).real, digits), round(complex(z).imag, digits))
        for z in values
    )


def _grid_orbit(m):
    """Full G-orbit intersection with the grid; section 7 proves C4 x| S2 suffices."""
    orbit = set()
    for power in range(4):
        basis = np.diag([1j**power, 1.0]).astype(complex)
        for element in (basis, SWAP @ basis):
            moved = element @ m @ np.linalg.inv(element)
            orbit.add(_rounded(np.ravel(moved)))
    return orbit


def _grid_matrices():
    return [np.array(e, dtype=complex).reshape(2, 2) for e in product(GRID, repeat=4)]


def test_ia1_hilbert_basis_of_the_torus_semigroup():
    generators = {(1, 1, 0, 0), (0, 0, 1, 1), (1, 0, 1, 0), (0, 1, 0, 1)}

    def decomposable(exponent):
        for generator in generators:
            if all(exponent[i] >= generator[i] for i in range(4)) and exponent != generator:
                return True
        return False

    irreducible = {
        e
        for e in product(range(5), repeat=4)
        if e != (0, 0, 0, 0) and e[0] + e[3] == e[1] + e[2] and not decomposable(e)
    }
    assert irreducible == generators


def test_torus_relation_uv_equals_w_wbar():
    rng = np.random.default_rng(0)
    for _ in range(200):
        b = rng.normal() + 1j * rng.normal()
        c = rng.normal() + 1j * rng.normal()
        assert np.isclose(abs(b) ** 2 * abs(c) ** 2, abs(b * c) ** 2)


def test_all_six_generators_are_invariant_under_the_full_group():
    rng = np.random.default_rng(1)
    for _ in range(500):
        m = rng.normal(size=(2, 2)) + 1j * rng.normal(size=(2, 2))
        phases = np.diag(np.exp(1j * rng.uniform(0.0, 2.0 * np.pi, 2)))
        for element in (phases, SWAP @ phases):
            moved = element @ m @ np.linalg.inv(element)
            assert np.allclose(real_family(moved), real_family(m), atol=1e-9)


def test_section_4_syzygies_hold_identically():
    rng = np.random.default_rng(2)
    for _ in range(400):
        m = rng.normal(size=(2, 2)) + 1j * rng.normal(size=(2, 2))
        a, b, c, d = m[0, 0], m[0, 1], m[1, 0], m[1, 1]
        u, v = abs(b) ** 2, abs(c) ** 2
        big_a, product_ad, w = a + d, a * d, b * c
        s, q, r = u + v, abs(a - d) ** 2, (a - d) * (u - v)
        r_bar = np.conj(a - d) * (u - v)
        z1 = big_a**2 - 4 * product_ad
        z2 = np.conj(big_a) ** 2 - 4 * np.conj(product_ad)
        z3 = s**2 - 4 * w * np.conj(w)

        assert np.isclose(q**2, z1 * z2)
        assert np.isclose(r**2, z1 * z3)
        assert np.isclose(r_bar**2, z2 * z3)
        assert np.isclose(r * r_bar, q * z3)
        assert np.isclose(q * r_bar, z2 * r)
        assert np.isclose(q * r, z1 * r_bar)


def test_ia4_q_is_pointwise_determined_by_z1():
    """Pointwise redundancy of Q.  This does NOT bear on proposition IA-3."""
    rng = np.random.default_rng(3)
    for _ in range(300):
        m = rng.normal(size=(2, 2)) + 1j * rng.normal(size=(2, 2))
        a, d = m[0, 0], m[1, 1]
        z1 = (a + d) ** 2 - 4 * a * d
        assert np.isclose(abs(a - d) ** 2, abs(z1))


def test_ia5_holomorphic_family_misses_both_degeneration_pairs():
    scalar = 1.7 * np.eye(2, dtype=complex)
    jordan = scalar + np.array([[0.0, 0.8], [0.0, 0.0]], dtype=complex)
    chiral = np.diag([1.0, 2.4]).astype(complex)
    triangular = chiral + np.array([[0.0, 0.8], [0.0, 0.0]], dtype=complex)

    for ideal, degenerate in ((scalar, jordan), (chiral, triangular)):
        assert np.allclose(holomorphic_family(ideal), holomorphic_family(degenerate))
        assert not np.allclose(real_family(ideal), real_family(degenerate))
        assert not np.isclose(real_family(ideal)[3], real_family(degenerate)[3])


def test_section_7_structured_grid_holomorphic_family_has_cross_orbit_collisions():
    """Section 7 proves the finite subgroup gives full-G orbit intersections on this grid."""
    buckets = {}
    for m in _grid_matrices():
        buckets.setdefault(_rounded(holomorphic_family(m)), []).append(m)
    collision_pairs = 0
    cross_orbit_pairs = 0
    for members in buckets.values():
        for first, second in combinations(members, 2):
            collision_pairs += 1
            if _rounded(np.ravel(second)) not in _grid_orbit(first):
                cross_orbit_pairs += 1
    assert collision_pairs == 2950
    assert cross_orbit_pairs == 1000


def test_section_7_structured_grid_real_family_has_no_cross_orbit_collisions():
    buckets = {}
    for m in _grid_matrices():
        buckets.setdefault(_rounded(real_family(m)), []).append(m)
    collision_pairs = 0
    cross_orbit_pairs = 0
    for members in buckets.values():
        for first, second in combinations(members, 2):
            collision_pairs += 1
            if _rounded(np.ravel(second)) not in _grid_orbit(first):
                cross_orbit_pairs += 1
    assert collision_pairs == 1950  # the test would be vacuous without forced collisions
    assert cross_orbit_pairs == 0
